name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.4.3=pyhd8ed1ab_3
  - folium=0.14.0=pyhd8ed1ab_0
  - geopy=2.3.0=pyhd8ed1ab_0
  - hvplot=0.8.2=pyhd8ed1ab_0
  - intake-esm=2021.8.17=pyhd8ed1ab_0
  - matplotlib=3.5.3=py37h89c1867_2
  - numpy=1.21.6=py37h976b520_0
  - pandas=1.3.5=py37he8f5f7f_0
  - xarray=0.20.2=pyhd8ed1ab_0
  - s3fs
  - vim
